name: serve-test

x-override: &override
  container_name: serve-backend_test
  volumes:
    - configs:/var/serve/configs
    - models:/var/serve/models
  command: webserver

volumes:
  configs:
  models:

services:
  backend:
    <<: *override

  backend-cpu:
    <<: *override

  traefik:
    container_name: serve-traefik_test
    volumes:
      - configs:/etc/traefik/configs
    ports:
      - 7500:80
      - 7510:8080

  sentinel:
    container_name: serve-sentinel_test

  database:
      container_name: serve-database_test

  # Same image as the backend, but with a different command
  # Runs the tests inside the container, calling the backend
  tester:
    image: ghcr.io/links-ads/serve-backend:${PROJECT_VERSION:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - configs:/var/serve/configs
      - models:/var/serve/models
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=false  # assume backend runs them 
    depends_on:
      database:
        condition: service_healthy
      traefik:
        condition: service_healthy
    container_name: serve-tester_test
    command: test
    tty: true
