version: '3'

volumes:
  configs:
  models:
  zips:

services:
  backend:
    container_name: serve-backend_test
    volumes: 
      - configs:/var/serve/configs
      - models:/var/serve/models
      - zips:/var/serve/zips
    ports:
      - 7510:5000
    command: pytest -sv --cov-report=term --log-cli-level=${LOG_LEVEL:-info} --cov=src tests/
    tty: true

  traefik:
    container_name: serve-traefik_test
    ports:
      # The HTTP port
      - 7500:80
    volumes:
    # dynamic configurations
      - configs:/etc/traefik/configs

  sablier:
    container_name: serve-sablier_test
