version: '3'

volumes:
  psgdata:
  pgAdmin4data:

services:
  backend:
      volumes: 
        - ./data/configs:/var/serve/configs
        - ./data/models:/var/serve/models
      ports:
        - 7510:5000
      command: uvicorn triton_serve.wsgi:app --root-path ${API_ROOT_PATH:-/} --host 0.0.0.0 --port 5000 --use-colors

  traefik:
    ports:
      # The HTTP port
      - 7500:80
      # The Web UI (enabled by --api.insecure=true)
      - 7520:8080
    volumes:
    # dynamic configurations
      - ./data/configs:/etc/traefik/configs

  database:
    volumes:
        - psgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
