name: serve-test

x-override: &override
  container_name: serve-backend_test
  volumes:
    - configs:/var/serve/configs
    - models:/var/serve/models
  command: test
  tty: true

volumes:
  configs:
  models:

services:
  backend:
    <<: *override

  backend-cpu:
    <<: *override

  traefik:
    container_name: serve-traefik_test
    volumes:
      - configs:/etc/traefik/configs
    ports:
      - 7500:80
      - 7510:8080

  celery-sentinel:
    container_name: serve-celery-sentinel_test

  database:
      container_name: serve-database_test
