version: '3'

volumes:
  config_files:

services:
# To test inference [REMOVE]
  triton_1:
      image: nvcr.io/nvidia/tritonserver:23.07-py3
      expose:
        - "8000"
        - "8001"
        - "8002"
      shm_size: '256m'
      volumes:
        - ./model_repository:/models
      command: ["tritonserver", "--model-repository=/models"]

      depends_on:
        - traefik
      labels:
      - sablier.enable=true
      - sablier.group=tritons

  backend:
      image: backend:latest
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        - config_files:/config_files
      depends_on:
        - traefik

  traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
    # static configuration
      - ./traefik_config/static:/etc/traefik
    # dynamic configuration
      - config_files:/config_files
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  sablier:
    image: acouvreur/sablier:1.4.0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - traefik.enable=true
      # Dynamic Middleware
      - traefik.http.middlewares.dynamic.plugin.sablier.names=sablier_tritons
      - traefik.http.middlewares.dynamic.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.dynamic.plugin.sablier.sessionDuration=1m
      - traefik.http.middlewares.dynamic.plugin.sablier.dynamic.theme=hacker-terminal
      # Blocking Middleware
      - traefik.http.middlewares.blocking.plugin.sablier.names=sablier_tritons
      - traefik.http.middlewares.blocking.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.blocking.plugin.sablier.sessionDuration=1m
      - traefik.http.middlewares.blocking.plugin.sablier.blocking.timeout=30s
      # Group Middleware
      - traefik.http.middlewares.group.plugin.sablier.group=sablier
      - traefik.http.middlewares.group.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.group.plugin.sablier.sessionDuration=1m
      - traefik.http.middlewares.group.plugin.sablier.blocking.timeout=30s
