name: serve-dev

x-override: &override
  volumes: 
    - ./data/configs:/var/serve/configs
    - ./data/models:/var/serve/models
    - ./src/:/app/src:ro
  ports:
    - 7510:5000
  command: webserver

services:
  backend:
    <<: *override
  
  backend-cpu:
    <<: *override

  traefik:
    ports:
      # The HTTP port
      - 7500:80
      # The Web UI (enabled by --api.insecure=true)
      - 7520:8080
    volumes:
    # dynamic configurations
      - ./data/configs:/etc/traefik/configs

  database:
      ports:
        - 7530:5432
