x-backend-base: &backend-base
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
      args:
      - TARGET=${TARGET:-dev}
      - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION:-525.125.06}
      - UBUNTU_VERSION=${UBUNTU_VERSION:-22.04}
      - PYTHON_VERSION=${PYTHON_VERSION:-3.10.12}
    image: ghcr.io/links-ads/serve-backend:${PROJECT_VERSION:-latest}
    hostname: backend
    container_name: serve-backend
    runtime: ${DOCKER_RUNTIME:-runc}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              count: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.serve-backend.rule=PathPrefix(`/serve`)
      - traefik.http.routers.serve-backend.entrypoints=http
      - traefik.http.routers.serve-backend.middlewares=serve-backend-stripprefix
      - traefik.http.middlewares.serve-backend-stripprefix.stripprefix.prefixes=/serve
    depends_on:
      database:
        condition: service_healthy
      traefik:
        condition: service_healthy
      sablier:
        condition: service_started

volumes:
  psgdata:
    driver: local

services:
  database:
      container_name: serve-database
      image: postgres:16.1-alpine3.18
      environment:
        POSTGRES_USER: ${DATABASE_USER:-postgres}
        POSTGRES_PASSWORD: ${DATABASE_PASS:-postgres}
        POSTGRES_DB: ${POSTGRES_DB:-serve_db}
      env_file:
        - .env
      volumes:
        - psgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USER:-postgres} -d $${POSTGRES_DB:-serve_db}"]
        interval: 10s
        timeout: 10s
        retries: 5

  traefik:
    build:
      context: containers/traefik
      dockerfile: Dockerfile
      args:
        - TARGET=${TARGET:-dev}
    image: ghcr.io/links-ads/serve-traefik:${PROJECT_VERSION:-latest}
    command: --api.insecure=true --providers.docker
    container_name: serve-traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget --no-check-certificate --spider localhost:8080/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
  
  sablier:
    image: acouvreur/sablier:1.4.0
    container_name: serve-sablier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "10000"
    labels:
      - traefik.enable=true

  backend:
    <<: *backend-base
    profiles: ["gpu"]
  
  backend-cpu:
    <<: *backend-base
    deploy: {}
    profiles: ["cpu"]