name: triton-serve

networks:
  default:
    external: true
    name: serve-network

volumes:
  configs:
  models:

x-override: &override
  volumes:
    - configs:/var/serve/configs
    - models:/var/serve/models
  command: webserver
  restart: unless-stopped

services:

  database:
    restart: unless-stopped
  
  sentinel:
    restart: unless-stopped

  backend:
    <<: *override
  
  backend-cpu:
    <<: *override

  traefik:
    ports:
      # The HTTP port
      - 127.0.0.1:7500:80
      # The Web UI (enabled by --api.insecure=true)
      - 127.0.0.1:7520:8080
    volumes:
      # dynamic configurations
      - configs:/etc/traefik/configs
    restart: unless-stopped
