"""init

Revision ID: af7db8f0dc88
Revises:
Create Date: 2024-07-23 12:30:01.663902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af7db8f0dc88"
down_revision: str | None = None
branch_labels: str | (Sequence[str] | None) = None
depends_on: str | (Sequence[str] | None) = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("host_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_name", sa.String(), nullable=False),
        sa.Column("num_cpus", sa.Integer(), nullable=False),
        sa.Column("total_memory", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("host_id"),
    )
    op.create_table(
        "models",
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("model_version", sa.Integer(), nullable=False),
        sa.Column("model_uri", sa.String(), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum(
                "UNK",
                "TENSORRT",
                "ONNX",
                "TORCHSCRIPT",
                "TENSORFLOW",
                "OPENVINO",
                "PYTHON",
                "DALI",
                "ENSEMBLE",
                name="modeltype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("dependencies", postgresql.ARRAY(sa.String()), nullable=True),
        sa.CheckConstraint("model_version > 0", name="model_version_positive"),
        sa.PrimaryKeyConstraint("model_name", "model_version", name="model_name_version"),
    )
    op.create_table(
        "services",
        sa.Column("service_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("service_image", sa.String(), nullable=False),
        sa.Column("container_id", sa.String(), nullable=True),
        sa.Column(
            "container_status",
            sa.Enum("STARTING", "ACTIVE", "ERROR", "STOPPED", "DELETED", name="servicestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inactivity_timeout", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_active_time", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("inactivity_timeout >= 0", name="non_negative_timeout"),
        sa.CheckConstraint("priority >= 0", name="non_negative_priority"),
        sa.PrimaryKeyConstraint("service_id"),
    )
    op.create_index(
        "service_name_idx", "services", ["service_name"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_table(
        "devices",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("memory", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["machines.host_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "model_mapping",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("model_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_name", "model_version"], ["models.model_name", "models.model_version"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.service_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "model_name", "model_version", name="service_model"),
    )
    op.create_table(
        "service_resources",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("cpu_count", sa.Integer(), nullable=False),
        sa.Column("shm_size", sa.Integer(), nullable=False),
        sa.Column("mem_size", sa.Integer(), nullable=False),
        sa.Column("environment_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("cpu_count > 0", name="positive_cpu_count"),
        sa.CheckConstraint("mem_size > 0", name="positive_mem_size"),
        sa.CheckConstraint("shm_size > 0", name="positive_shm_size"),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.service_id"],
        ),
        sa.PrimaryKeyConstraint("service_id"),
    )
    op.create_table(
        "device_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("allocation_percentage", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "allocation_percentage > 0 AND allocation_percentage <= 100", name="valid_allocation_percentage"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.service_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_allocations")
    op.drop_table("service_resources")
    op.drop_table("model_mapping")
    op.drop_table("devices")
    op.drop_index("service_name_idx", table_name="services", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("services")
    op.drop_table("models")
    op.drop_table("machines")
    # ### end Alembic commands ###
