name: test

on:
  push:
    branches: [main,validation]
  pull_request:
    branches: [main,validation]

env:
  TARGET: test
  TRITON_VERSION: 23.07-py3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install ".[dev]"
      - name: Lint and format check
        run: |
          python -m black --check .
          python -m isort --check .
          python -m ruff check .
      - name: 'Create env file'
        run: |
          echo "${{ secrets.environment }}" > .env
      - name: Pull Triton image
        run: |
          docker pull "nvcr.io/nvidia/tritonserver:$TRITON_VERSION"
      - name: Run tests
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.test.yml
          compose-flags: "-p serve-test --profile cpu"
          up-flags: "--build --abort-on-container-exit --exit-code-from backend-cpu"
          down-flags: "--volumes"
